version: "3.8"
services:
  api:
    build: .
    container_name: tasks_api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app

